format = """
${custom.toolbox}\
$jobs\
$cmake\
$cmd_duration\
$git_branch\
$directory\
$character"""



# enable when its possible to optionally put in between git_branch and the rest
#
# [git_status]
# format = '''([\($all_status$ahead_behind\)]($style)
# )'''

[custom.toolbox]
format = '[⬢ ]($style)'
command = 'echo YES'
when = 'test -e /run/.toolboxenv'
# when = ':'
style = 'purple'

[jobs]
symbol = ' '

[cmd_duration]
format = '[$duration ]($style)'

[git_branch]
format = '[ $symbol$branch ]($style)'
[directory]
format = '[$path]($style)( $read_only) '
truncation_length = 2
truncate_to_repo = true
read_only = '' # will replace read_only_symbol in next release
read_only_symbol = ''

