#!/bin/sh
# this file adds paths that should be available to user

# brew
[ -f "/home/linuxbrew/.linuxbrew/bin/brew" ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# pip
PATH=$PATH:$HOME/.local/bin

# gem
PATH=$PATH:"$HOME/.gem/ruby/*/bin"
