#!/bin/bash

# load shell init file
source ~/.shell

# the rest is only if it's an interactive shell
[[ $- != *i* ]] && return

# terminal options #
# cd by typing a path
shopt -s autocd

# ignore duplicate commands and commands prefixed by space in history
HISTCONTROL=ignoreboth

# load additional files
source "$HOME"/.shell/aliases.sh
source "$HOME"/.shell/functions.sh

if command -v starship > /dev/null; then
   eval "$(starship init bash)"
else
   echo "Starship not found, basic prompt will be used"

   PS1="\[$(tput bold)\]\[$(tput setaf 5)\]\w\\n\[$(tput setaf 3)\]\\$ \[$(tput sgr0)\]"
   export PS1
fi
