#!/usr/bin/env zsh

function updates_refresh {
   function update {
      ( checkupdates >! /tmp/zsh_updates_pending & )
   }

   [ -f /tmp/zsh_updates_pending ] || { update; return }

   for _ in /tmp/zsh_updates_pending(N.mh+1); do
      update
   done
}

# todo include aur
# todo always warn if kernel needs updating
function updates_pending {
   updates_refresh

   local packages=$(cat /tmp/zsh_updates_pending | wc -l)
   if [ "$packages" -gt 15 ]; then
      echo "pending pacman updates: $packages"
   fi
}

function system_report {
   if systemctl --failed > /dev/null; then
      echo 'there are failed system services'
      systemctl --failed

      sudo journalctl -p 3 -xb
   fi
}

#function list {
#   case $1 in
#      *.zip)
#         unzip -l "$1"
#         ;;
#      *.rar)
#         unrar l "$1"
#         ;;
#      *.tar.*)
#         echo 'unsupported'
#         ;;
#      *.tar)
#         tar tf $1
#         ;;
#      *)
#         echo 'unsupported archive \'$1\''
#   esac
#}
