#!/usr/bin/env zsh

## zsh options ##
HISTFILE=~/.zhistory
HISTSIZE=SAVEHIST=10000
setopt sharehistory extendedhistory append_history hist_ignore_dups hist_ignore_space

# no beeps
setopt no_beep

# dont overwrite stuff with redirection
setopt no_clobber

# error when glob doesnt match anything
setopt no_match

# cd into a directory by typing the path
setopt auto_cd

# save comments in history
setopt interactive_comments

# report when background job finishes
setopt notify

# dont kill jobs when shell exits
setopt no_hup

# long format for jobs
setopt long_list_jobs

# dont match dotfiles
setopt no_globdots

# better globs
setopt extendedglob
setopt no_caseglob

# nicer tab completion
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# generate compinit only once a day
autoload -Uz compinit

for _ in ~/.zcompdump(N.mh+24); do
   echo "Generating compinit, this may take a while.."
   compinit
done

compinit -C

# show dotfiles with tab completion
_comp_options+=(globdots)

# set window title
case $TERM in
    xterm*)
        precmd () { print -Pn "\e]0;%n in %~\a" }
        ;;
esac

[ -f ~/.profile ] && source ~/.profile

# load additional files (only if dotfiles exist)
if [ -d "$DOTFILES" ]; then
   source "$DOTFILES"/zsh/packages.zsh
   source "$DOTFILES"/zsh/functions.zsh
   source "$DOTFILES"/zsh/aliases.zsh
   source "$DOTFILES"/zsh/keybindings.zsh
   source "$DOTFILES"/shell/common.sh
   source "$DOTFILES"/shell/user-path.sh
else
   echo "Dotfiles not found only basic options were set"
fi

# remove duplicate paths
typeset -U PATH
export PATH
