#!/usr/bin/env zsh

# load shell init file (only if it exists)
[ -f ~/.shell ] && source ~/.shell

# the rest is only if it's an interactive shell
[[ -o interactive ]] || return

## zsh options ##
HISTFILE=~/.zhistory
HISTSIZE=SAVEHIST=10000
setopt sharehistory extendedhistory append_history hist_ignore_dups hist_ignore_space

# no beeps
setopt no_beep

# dont overwrite stuff with redirection
setopt no_clobber

# error when glob doesnt match anything
setopt no_match

# cd into a directory by typing the path
setopt auto_cd

# save comments in history
setopt interactive_comments

# report when background job finishes
setopt notify

# dont kill jobs when shell exits
setopt no_hup

# long format for jobs
setopt long_list_jobs

# dont match dotfiles
setopt no_globdots

# better globs
setopt extendedglob
setopt no_caseglob

# nicer tab completion
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# set window title
case $TERM in
    xterm*)
        precmd () { print -Pn "\e]0;%n in %~\a" }
        ;;
esac

autoload -Uz compinit

# load additional files (only if dotfiles exist)
if [ -d "$DOTFILES" ]; then
   source "$DOTFILES"/zsh/packages.zsh
   source "$DOTFILES"/zsh/functions.zsh
   source "$DOTFILES"/zsh/aliases.zsh
   source "$DOTFILES"/zsh/keybindings.zsh
else
   echo "Dotfiles not found only basic options were set"
fi

if command -v starship > /dev/null; then
   eval "$(starship init zsh)"
else
   echo "Starship not found, basic prompt will be used"
   PS1="\[$(tput bold)\]\[$(tput setaf 5)\]\w\\n\[$(tput setaf 3)\]\\$ \[$(tput sgr0)\]"
   export PS1
fi

# generate compinit only every 4 hours
for _ in ~/.zcompdump(N.mh+4); do
   echo "Generating compinit, this may take a while.."
   compinit
   clear
done

compinit -C

# show dotfiles with tab completion
_comp_options+=(globdots)

# remove duplicate paths
typeset -U PATH
export PATH
