#!/bin/bash
# run only in interactive shells
[[ $- != *i* ]] && return

# terminal options #
# cd by typing a path
shopt -s autocd

# ignore duplicate commands and commands prefixed by space in history
HISTCONTROL=ignoreboth

PS1="\[$(tput bold)\]\[$(tput setaf 5)\]\w\\n\[$(tput setaf 3)\]\\$ \[$(tput sgr0)\]"
export PS1

[ -f /etc/bashrc ] && source /etc/bashrc

# shellcheck source=../shell/profile
[ -f ~/.profile ] && source ~/.profile

# load additional files (only if dotfiles exist)
if [ -d "$DOTFILES" ]; then
   # shellcheck source=../shell/common.sh
   source "$DOTFILES"/shell/common.sh

   # shellcheck source=../shell/aliases.sh
   source "$DOTFILES"/shell/aliases.sh

   # shellcheck source=../shell/user-path.sh
   source "$DOTFILES"/shell/user-path.sh
else
   echo "Dotfiles not found only basic options were set"
fi
