#!/bin/bash

# load shell init file (only if it exists)
[ -f ~/.shell ] && source ~/.shell

# the rest is only if it's an interactive shell
[[ $- != *i* ]] && return

# terminal options #
# cd by typing a path
shopt -s autocd

# ignore duplicate commands and commands prefixed by space in history
HISTCONTROL=ignoreboth

# [ -f /etc/bashrc ] && source /etc/bashrc

# load additional files (only if dotfiles exist)
if [ -d "$DOTFILES" ]; then
   source "$DOTFILES"/shell/aliases.sh
else
   echo "Dotfiles not found only basic options were set"
fi

if command -v starship > /dev/null; then
   eval "$(starship init bash)"
else
   echo "Starship not found, basic prompt will be used"

   PS1="\[$(tput bold)\]\[$(tput setaf 5)\]\w\\n\[$(tput setaf 3)\]\\$ \[$(tput sgr0)\]"
   export PS1
fi
